[workspace]
resolver = "2"
members = [
    "crates/apex-binder",
    "crates/apex-discover",
    "crates/apex-lexer",
    "crates/apex-metadata",
    "crates/apex-syntax",
    "crates/apex-parser",
    "crates/apex-printer",
    "crates/apexls-cli",
    "crates/apexls-server",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
apex-binder = { path = "crates/apex-binder" }
apex-discover = { path = "crates/apex-discover" }
apex-lexer = { path = "crates/apex-lexer" }
apex-metadata = { path = "crates/apex-metadata" }
apex-syntax = { path = "crates/apex-syntax" }
apex-parser = { path = "crates/apex-parser" }
apex-printer = { path = "crates/apex-printer" }
